export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_FULFILLED= 'LOGIN_USER_FULFILLED'
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED'

export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING'
export const REGISTER_USER_FULFILLED= 'REGISTER_USER_FULFILLED'
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED'


export const LOGOUT_USER_PENDING = 'LOGOUT_USER_PENDING'
export const LOGOUT_USER_FULFILLED= 'LOGOUT_USER_FULFILLED'
export const LOGOUT_USER_REJECTED = 'LOGOUT_USER_REJECTED'

